[build]
  publish = "web-build"
  command = "npm run build:web"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run web"
  port = 19006
  publish = "web-build"